# action.yml
name: 'Testim CLI'
description: 'Run tests on Testim.io'
inputs:
  token:  # id of input
    description: 'Testim auth token'
    required: true
  project:
    description: 'Project ID'
    required: true
  grid:
    description: 'Grid to run the tests on'
    required: true
    default: "Testim-Grid"
  suite:
    description: 'The test suite to run'
    required: false
  base-url:
    description: 'Starting URL after browser opens'
    required: false
  result-label:
    description: 'Textual label to the remote runs'
    required: false
  timeout:
    description: 'Timeout period in milliseconds to abort the test run if a timeout has elapsed'
    required: false
  branch:
    description: 'Branch (by name) to run the tests on'
    required: false
  parallel:
    description: 'How many tests should run in parallel'
    required: false
    default: '1'
  retries:
    description: 'Max number of retries'
    required: false
  label:
    description: 'Run specific tests that include the specified labels' 
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.project }}
    - ${{ inputs.grid }}
    - ${{ inputs.suite }}
    - ${{ inputs.base-url }}
    - ${{ inputs.result-label }}
    - ${{ inputs.timeout }}
    - ${{ inputs.branch }}
    - ${{ inputs.parallel }}
    - ${{ inputs.retries }}
    - ${{ inputs.label }} 
